### ISSUE TITLE
Refine API help screen

### ISSUE THREAD

**Issue by KralMar** [plan-net/core4#72] opened 2019-08-30 08:08 UTC
The current help-screen looks overfilled.
We should redefine the look and content of help-pages.

Action required:
* Identify the relevant information for a help screen
* Review existing APIs in the core4os repository with regard to these elements (completeness, quality)
* Define necessary rework

**Comment by m-rau** [comment] 2019-09-02 04:09
## relevant information in help

current information is displayed as a table.. To make the help more appealing I suggest to have 2 sections:

1. a header
1. the main area

#### header

should display the following information condensed, i.e. not as a table but nicely formatted. The field names (tag, protected, icon, etc.) do not need to be displayed or very much put into the background.

* title
* subtitle (qual_name if not specified)
* author
* tags
* icon
* protected (represented with a visual)
* created at
*  enter_url (not to be displayed but available as a link, e.g. by clicking on the title)

#### main area

This is a continuous flow text with the doc string and the formatted docstrings of the handler methods

#### further details

The following information should be available only if the user requests further details:
* resource id
* container
* class args
* pattern
* endpoints

# next step
1. draft the layout
1. continue with review and specification of rework required

**Comment by m-rau** [comment] 2019-09-09 10:38
reassigned ticket due to current workload and priorities

**Comment by m-rau** [comment] 2019-09-10 18:16
## review and rework required
see here: https://docs.google.com/document/d/1_Ykk1KvFgFavmon4qFEEIau4AGt1cGJEdt8ai-D3j98/edit?usp=sharing

## next steps
* implement the changes
* check with @marekmru when/who/how to work on the redesign

**Comment by m-rau** [comment] 2019-09-12 05:46
Pending changes:
* core4.api.v1.request.role.main.RoleHandler - improve help, see #58
* core4.api.v1.request.standard.profile.ProfileHandler - implement profile page, see #29
* core4.api.v1.request.standard.info.InfoHandler - create a page with the endpoints' card listing; furthermore another overview screen would help to facilitate the API review
* core4.api.v1.request.queue.system.SystemHandler - provide screen and card with maintenance information

**Low** priority changes. Need to discuss when and if we wish to implement
* core4.api.v1.request.queue.job.JobPost - have a nicely formatted job listing, possible with actions to restart, kill and remove
* core4.api.v1.request.standard.login.LoginHandler - have a consolidated page with links for password update, password reset, logout
* core4.api.v1.request.standard.logout.LogoutHandler - resolve the issue to logout from basic auth

**Comment by m-rau** [comment] 2019-09-25 19:02
update on all tasks still in scope of this issue:
* core4.api.v1.request.standard.info.InfoHandler - created dedicated task #98 
* core4.api.v1.request.queue.system.SystemHandler - has been implemented, see 78af10eb579107b65125a3975adeca6a0f00fe43
* core4.api.v1.request.queue.job.JobPost - created dedicated task #99
* core4.api.v1.request.standard.login.LoginHandler - created dedicated task #100
core4.api.v1.request.standard.logout.LogoutHandler - created dedicated task #100

### next step
* provide simple API help screen with the complete example of markup - rationaiil is to provide a blueprint for improved API help screen formatting and layout

**Comment by m-rau** [comment] 2019-09-25 19:55
this [request handler source code](https://github.com/m-rau/core4/blob/mra.help/tests/other/test_help.py) (own fork) renders as follows:

* the class docstring with [intro.pdf](https://github.com/plan-net/core4/files/3654501/intro.pdf)

* the ``GET`` method docstring with [get.pdf](https://github.com/plan-net/core4/files/3654495/get.pdf)

**Comment by marekmru** [comment] 2019-09-26 16:14
Please review https://github.com/plan-net/core4/pull/101 (and close)

**Comment by MarkusKral** [comment] 2019-10-01 11:53
Hi @marekmru:

Implementation looks good so far, from @m-rau s I am only missing the "protected" visual within the header.

Also, there is always a section "HTTP Method Summary" rendered, even though some Handlers (e.g. the EventHandler) do not specify any http-methods. Can we remove this section if no method is given?

**Comment by marekmru** [comment] 2019-10-04 11:25
@KralMar this is fixed, there is a pull request.

**Comment by MarkusKral** [comment] 2019-10-04 12:10
Hi @marekmru :

currently the protected icon is always redered,
even when the backend renderes the template with protected=False.

Steps to reproduce: Search for an Container, give it the flag protected=True.
Show the info of the container within the widgetmanager.

Whatever the protected Flag, the lock is always shown.

(I had a look at the backend, it does "pass on" the protected variable to the template correctly.)

**Comment by marekmru** [comment] 2019-10-04 12:57
@KralMar 
Had to cast python "True" to javascript true. Is fixed.

**Comment by MarkusKral** [comment] 2019-10-04 13:59
Confirmed working.

Branch merged and deleted.

**Closed by MarkusKral** 2019-10-04 13:59 UTC
